use_frameworks!

platform :ios, '9.0'

target 'MBProgressHUDExtreme_Example' do
  pod 'MBProgressHUDExtreme', :path => '../'

  target 'MBProgressHUDExtreme_Tests' do
    inherit! :search_paths

    
  end
end
